export const ADD_ROW = 'ADD_ROW';
export const DELETE_ROW = 'DELETE_ROW';
export const CREATE_TABLE = 'CREATE_TABLE';
export const INCREMENT_CELL_AMOUNT = 'INCREMENT_CELL_AMOUNT';
export const HIGHlIGHT_RELATED_CELLS = 'HIGHlIGHT_RELATED_CELLS';